

server:
  port: 9528



spring:
  datasource:
    druid:
      mysql:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST:tianyafu}:${MYSQL_PORT:3306}/${MYSQL_DATABASE_NAME:graduation_project}?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:root}
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      aop-patterns: com.hwinfo.jkdv3earlywarning.business.service.*
  application:
    name: graduation-season-project
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  # 这个要为true 否则前端的delete请求是发不成功的
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true
#    mode: LEGACYHTML5
#    prefix: classpath:/templates/
#    suffix: .html
#    encoding: UTF-8
#    check-template-location: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.graduation.domain
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  config: classpath:log4j2.yml
  level:
    com.graduation.mapper: debug

swagger:
  show: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.graduation.domain
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl